apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    team: dev
    versions: v1
    app: nginx
    env: production
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80